### ISSUE TITLE
Not getting any Accepted Hashes

### ISSUE THREAD

**Issue by joemcdoes** [cazala/coin-hive-stratum#28]
I tried using this but I'm getting no valid shares. I get no errors on the JS console. If I check _miner.getTotalHashes()_ I get a high number but _miner.getAcceptedHashes()_ returns 0. The output form _nodejs_ looks like this:

[Oct 20th 03:56] message from pool to miner: {"jsonrpc":"2.0","method":"job","params":{"blob":"0606e8a9a9cf05ad2cbcb18e23a7a0a300087241e663ca3f7304d6480329324ce7a71d110ebf3c0000000046e2bd25b8e73d20866d8faab0c27f97ad704371bbc0e9ee871fa73c0eafd76e06","job_id":"18018","target":"cf8b0000"}}

[Oct 20th 03:56] message sent to miner: {"type":"job","params":{"blob":"0606e8a9a9cf05ad2cbcb18e23a7a0a300087241e663ca3f7304d6480329324ce7a71d110ebf3c0000000046e2bd25b8e73d20866d8faab0c27f97ad704371bbc0e9ee871fa73c0eafd76e06","job_id":"18018","target":"cf8b0000"}}

[Oct 20th 03:57] message from pool to miner: {"jsonrpc":"2.0","method":"job","params":{"blob":"0606a4aaa9cf05ad2cbcb18e23a7a0a300087241e663ca3f7304d6480329324ce7a71d110ebf3c0000000073dd1676e9d042685c2df487189c9b3015bbca89f1d6a1cefc531f602205a35008","job_id":"18019","target":"cf8b0000"}}

[Oct 20th 03:57] message sent to miner: {"type":"job","params":{"blob":"0606a4aaa9cf05ad2cbcb18e23a7a0a300087241e663ca3f7304d6480329324ce7a71d110ebf3c0000000073dd1676e9d042685c2df487189c9b3015bbca89f1d6a1cefc531f602205a35008","job_id":"18019","target":"cf8b0000"}}

**Comment by sunk818** [comment]
What is your hash rate? If you go to coinhive and just run their test miner on the home page, you can get your hash rate. What is the difficulty for the pool you are on? If difficulty is too high, you can hash away but none will be accepted because difficulty is too high and/or the new block comes online and you have to start all over. Try here https://usxmrpool.com/#getting_started -- their starting difficulty on port 2222 is 3000, so even a device hashing 20 H/s should be able to submit one acceptable hash before the block changes.

**Comment by joemcdoes** [comment]
I can mine on CoinHive with no problem. It's only when I try to use an external pool that I run into that problem.

**Comment by sunk818** [comment]
I asked you some questions. Are you able to answer?

Coin hive credits you for all hashes but you need 3.8 billion hashes or so to get 0.5 xmr. Mining pools work usually credit you when a block is solved and just gives a percentage based on your accepted shares.

**Comment by joemcdoes** [comment]
Great! I'll try with that pool and let you know how it goes.

Thanks again
