### ISSUE TITLE
Can coin hive shut this down?

### ISSUE THREAD

**Issue by hayzamjs** [cazala/coin-hive-stratum#32]
Amazing project, but was just wondering, is this using just the javascript cryptonight miner of coinhive or some of their servers too? If it is using some of server side of coinhive too, will this project get taken down?

**Comment by sunk818** [comment]
I don't see how they can shut this down? The JavaScript can be updated by coinhive, but the current version is not a secret. Worst case, you'd have to host it yourself, right?

I think they are feeling pressure because they reduced their minimum payout three days ago to 0.05 XMR for a fee of 0.01 XMR. They are taking a 20% fee, but the payout threshold from 0.5 XMR to 0.05 XMR.

**Comment by cazala** [comment]
Well I suppose they could tweak the protocol to break it if they wanted, but you could still use a copy of the miner + this proxy on a different pool.

**Comment by hayzamjs** [comment]
Yeah, yesterday I guess they did something to break the miner on mobile devices, or is it just me?

**Comment by cazala** [comment]
there was a DNS breach yesterday https://coinhive.com/blog/dns-breach
