### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by Thawwed** [cazala/coin-hive-stratum#56]
I have never worked with websocket/proxy type stuff, so this is new to me.
I keep getting the following error message:
> Websocket connection to 'wss://localhost:8892' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I used certbot to generate and install my SSL certificate. Everything over https:// works fine.

I'm wondering if this is an Apache config issue. I modified a few config files but to no avail.

**Comment by cazala** [comment]
are you creating an https server and passing it to the proxy like this? https://github.com/cazala/coin-hive-stratum#how-can-i-make-my-proxy-work-with-wss

**Comment by Thawwed** [comment]
I did not do that. How do I do that? Do I add that to my javascript or is this done elsewhere?

**Comment by cazala** [comment]
save this as your `proxy.js`

```js
// Create your proxy
const createProxy = require("coin-hive-stratum");
const proxy = createProxy({
  host: "la01.supportxmr.com",
  port: 3333
});


// Create an HTTPS server
const server = require("https").createServer({
  key: fs.readFileSync("./server.key"),
  cert: fs.readFileSync("./server.crt")
});
server.listen(8892);

// Pass your HTTPS server to the proxy
proxy.listen({
  server: server
});
```

and just run it like `node proxy`, you should be able to access it from `wss://localhost:8892`.

you will need those `server.key` and `server.crt` certificates in order to work. you can generate self-signed certificates by running this:

```
openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt
```

but those certificates won't be trusted by your browser, so you will get an alert, so you will have to add them to your trusted certificates manually

I have no idea about Apache tho, it might need some extra configuration.

**Comment by thelemonenergy** [comment]
i got it to run within http and just tried this for https.
i did not configure https for my server since i want to keep flexible ssl on cloudflare.
i copied a valid key and crt in the same folder my new proxy.js is inside.

Now i get a "Error: Cannot find module 'coin-hive-stratum'
" error when i try to run it with node proxy (also tried as root).
can you help me out?

**Comment by Thawwed** [comment]
I got that same error

**Comment by cazala** [comment]
do
npm init --yes && npm i --save coin-hive-stratum 
in the same dir where you have your proxy.js file

**Comment by thelemonenergy** [comment]
Now i have a new error
"Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
"

Is this below here correct? proxy.js and key,crt and pem file in the same folder.
// Create an HTTPS server
const server = require("https").createServer({
  key: "mysite.key",
  cert: "mysite.crt"
});

**Comment by cazala** [comment]
it looks like your .crt file is invalid, that's not a coin-hive-stratum error, that's node's https complaining.
are those paths to the files right?

Sent from my iPhone

On Nov 7, 2017, at 8:31 PM, thelemonenergy <notifications@github.com<mailto:notifications@github.com>> wrote:


Now i have a new error
"Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
"

Is this below here correct? proxy.js and key,crt and pem file in the same folder.
// Create an HTTPS server
const server = require("https").createServer({
key: "mysite.key",
cert: "mysite.crt"
});

**Comment by thelemonenergy** [comment]
key: fs.readFileSync("./mysite.key"),
cert: fs.readFileSync("./mysite.crt")
seem to work.

new error now (a new error is always a step forward)
ReferenceError: fs is not defined

**Comment by thelemonenergy** [comment]
I worked around it:
I disabled ssl for my domain:port in a page rule in cloudflare.
Now it works :)

**Comment by cazala** [comment]
Nice :D !

there was a line missing in the code from [my comment above](https://github.com/cazala/coin-hive-stratum/issues/56#issuecomment-342500929): 

```js
const fs = require("fs");
```

I just edited the comment and added it to the readme
