### ISSUE TITLE
Multiples Miners

### ISSUE THREAD

**Issue by vphelipe** [cazala/coin-hive-stratum#68]
I have a total of 10,000 miners and this script unfortunately does not support. It works for a few minutes and stops, hashrate drops dramatically.

**Comment by cazala** [comment]
could you try setting the `purgeInterval` to `-1`? if you are using the cli you can use the flag `--purge-interval=-1`

**Comment by cazala** [comment]
i haven't tested with 10k miner but we have almost 4k running very stable with the latest version

**Comment by CineXMike** [comment]
Try using 2.3.0 maybe that will fix your issues!
Unless not solved you can open this issue aigan!

**Comment by vphelipe** [comment]
After not being able to use your code, I moved to:

https://github.com/deepwn/deepMiner

and I'm happy now;)

**Comment by cazala** [comment]
that's like coin-hive-stratum v1.. it creates 1 tcp connection per ws, if it works for you fine but watch out once the pools start banning you

**Comment by vphelipe** [comment]
I tried several times to use your code, but it does not work. Only with one connection per miner and yet he falls fast. I have a very robust server but it does not work properly.

**Comment by cazala** [comment]
i'm sad to hear that, we have +4k miners working currently with version v2.5.0, if you want me to help you out let me know.

**Comment by vphelipe** [comment]
We can try! I will install again and I will try to use, using multi colors with the deepminer I got my highest hashrate rate. Much better than the x25 code.

**Comment by vphelipe** [comment]
Erros:

job submitted (95fb10ce-95b9-41d6-bce9-4280c4026d26): 147879293001530
unauthenticated job submission (95fb10ce-95b9-41d6-bce9-4280c4026d26)
job submitted (7470f4f7-a77a-4253-93c1-adffd0182808): 214477429832535
unauthenticated job submission (7470f4f7-a77a-4253-93c1-adffd0182808)
job submitted (3a3ab9d0-79eb-4567-a60a-d2a925193b87): 857124436303062
unauthenticated job submission (3a3ab9d0-79eb-4567-a60a-d2a925193b87)
job submitted (4ff90deb-1114-4e08-9d5d-39a80512526a): 995609431820954
unauthenticated job submission (4ff90deb-1114-4e08-9d5d-39a80512526a)
job submitted (7c5d1075-dba0-4879-9908-ddc931a71ea3): 128631720997553
unauthenticated job submission (7c5d1075-dba0-4879-9908-ddc931a71ea3)
job submitted (921de502-7196-4d4e-b2ec-a998fc2f352f): 540031259117783
unauthenticated job submission (921de502-7196-4d4e-b2ec-a998fc2f352f)
job submitted (77a04fe7-8345-43ad-9044-ad396fc667ee): 360291272178360
unauthenticated job submission (77a04fe7-8345-43ad-9044-ad396fc667ee)
job submitted (17194820-b532-4328-aac3-2db136408069): 135344237716692
unauthenticated job submission (17194820-b532-4328-aac3-2db136408069)
job submitted (fbbd8b55-d0ec-48b5-8fce-8dd08ec22f4a): 965173701128296
unauthenticated job submission (fbbd8b55-d0ec-48b5-8fce-8dd08ec22f4a)
job submitted (e3f34a00-44a2-4f1c-ba62-7f60ed7b2909): 943427479403874
unauthenticated job submission (e3f34a00-44a2-4f1c-ba62-7f60ed7b2909)
job submitted (b390f6c2-a750-44ac-9a26-c6dd0b723a9c): 477891476381222
unauthenticated job submission (b390f6c2-a750-44ac-9a26-c6dd0b723a9c)
job submitted (8501c05b-6ec7-4df3-955e-e91ba4d47e4e): 674180504273720
unauthenticated job submission (8501c05b-6ec7-4df3-955e-e91ba4d47e4e)
job submitted (8501c05b-6ec7-4df3-955e-e91ba4d47e4e): 674180504273720
unauthenticated job submission (8501c05b-6ec7-4df3-955e-e91ba4d47e4e)
job submitted (5f8d34a9-a6cd-43b5-a804-4ffd822bc9d0): 355364943266000
unauthenticated job submission (5f8d34a9-a6cd-43b5-a804-4ffd822bc9d0)
job submitted (28bdec88-6fc3-4c41-b443-5307a9d15121): 835656496525698
unauthenticated job submission (28bdec88-6fc3-4c41-b443-5307a9d15121)
job submitted (9d811af9-48d6-4842-8baf-5c08352ad1eb): 530516213377855
unauthenticated job submission (9d811af9-48d6-4842-8baf-5c08352ad1eb)

**Comment by cazala** [comment]
which pool are you on?

**Comment by cazala** [comment]
those job_id's look like ETN ones

**Comment by vphelipe** [comment]
The pool I use is minercircle.com, with the deepminer and works very well.

I know several pool are banning, so I wanted to use your code.

I am testing now on minergate.com and my hashrate does not exceed 15 / HS using its code, being that with the deep miner at that moment stands at 30KH / s

**Comment by vphelipe** [comment]
Could you test in the pool minercircle.com or minergate.com? These 2 pools have low difficult, so you get a higher hashrate.

**Comment by cazala** [comment]
I just realised that you are using an old version of the proxy. That `unauthenticated job submission` error doesn't exist since `v2.1.0`, and the latest version at this moment is `v2.5.0`.

You can check what version you are using by looking at the `package.json`:

```
cat node_modules/coin-hive-stratum/package.json
``` 

you will see that you are using `v2.0.x`. A lot of bugs have been fixed since then.

Please install the latest version `npm install --save coin-hive-stratum@latest`, you should see something like:

```
+ coin-hive-stratum@2.5.3
added 1 package and updated 1 package in 2.851s
```

if that doesn't work delete node_modules and reinstall: `rm -rf node_modules && npm install`

please let me know how it goes with the last version.

**Comment by cazala** [comment]
oh and btw, regarding the hashrate: a lower difficulty won't mean higher hashrate, only higher job submission rate. the hashrate is the amount of shares times the difficulty. so if you mine on a pool with a difficulty of 256, you will send for example 20 jobs per minute, and if you mine on a pool with a difficulty of 1000 you will send 5 jobs per minute. 4 times less, because the diff is 4 times higher, but also your jobs will give you 4 times more shares than the ones from the pool with lower difficulty.

20 jobs at difficulty 256 in 1 minute means: 20 * 256 = 5000 shares: 5000hash / 60sec = 83.33 h/s
5 jobs at difficulty 1000 in 1 minute means: 5 * 1000 = 5000 shares, again: 5000hash / 60sec = 83.33 h/s

Of course when doing webmining you want to submit jobs fast, because your user might not stay that long in each page, and you want the miners to be able to submit jobs in that short span of time, but in my experience i've gotten the best results mining on supportxmr.com, just my two cents.

**Comment by vphelipe** [comment]
WOW! My version really was old, with the current version working well, I'll wait until tomorrow at the peak of miners to see if I see something wrong. Thanks for your help!!!

**Comment by cazala** [comment]
glad to help ^.^ please let me know tomorrow how it goes

**Comment by cazala** [comment]
btw, are you still running with `--max-miners-per-connection=1`?

**Comment by vphelipe** [comment]
No, I'm using the default value. I have a dedicated server, and I can only increase my hashrate using a cluster.js to run the code on all processor cores. The only inconvenience is that my /stats shows the values of only one of the processes, but works much better for those who have many nucles in the processor.

**Comment by cazala** [comment]
yes the /stats, /miners and /connections endpoints are far from being and actual metrics api, it's more of a debugging tool. you can run a cluster using pm2 and get better metrics, like shares per minute and the right amount of miners and connections, have you tried it?

**Comment by vphelipe** [comment]
I do not know yet how to explain, but now it has started to decrement my hashrate, when I run with cluster.js. I can not see errors in the logs ...

**Comment by vphelipe** [comment]
If you can test in the minercircle.com pool, you will see that after a few minutes the hashrate begins to decrease until it reaches zero, something is wrong. In the pool supporxmr.com seems to work fine, but in the pool minercircle.com works for only a few minutes...

**Comment by cazala** [comment]
i will test it and get back to you, i seems that miners get unauthorized after a while, maybe their keepalive is different than the one used by other pools, i ll run some tests and let you know

**Comment by vphelipe** [comment]
Thank you cazala!
