### ISSUE TITLE
Accepted Hashes' really low?

### ISSUE THREAD

**Issue by osfcacuk** [cazala/coin-hive-stratum#95]
Not sure if this is an issue or not but when logging the data from the miner the accepted hashes is really low compared to the total hashes.

Hashes Per Second: 16.064368907281676
Total Hashes: 6900
Accepted Hashes: 3

Is this normal or am I doing something wrong?

**Comment by cazala** [comment]
It's working as expected. When using coin-hive-stratum, I notify when a share was accepted. The amount of hashes that represent that share depend on the pool you are mining on.

When you use coinhive.com, the difficulty is 256, that's why you see the accepted hashes to add on batches of 256. 

If you mine on supportxmr.com, since the difficulty is 1000, each share accounts for 1000 hashes, so when you see `Accepted Hashes: 3` it would equal to 3000 hashes. Since the proxy doesn't know the difficulty of the pool you are mining on, I can't hardcode a +1000 for each share, because that might not make sense for other pools. 

Here is a more detailed explanation: #83

**Comment by osfcacuk** [comment]
Ah, thank you, that makes perfect sense now!
